version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    #environment:
    #  JVM_OPTS:
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: build/test-results/test
      - run:
          name: Build
          command: ./gradlew jar
      - store_artifacts:
          path: build/libs/*.jar
