version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v2-{{ checksum "build.gradle" }}
            - deps-v2
      - run:
          name: Run Tests
          command: ./gradlew check
      - store_test_results:
          path: build/test-results/test
      - run:
          name: Build
          command: ./gradlew build
      - persist_to_workspace:
          root: build
          paths:
            - konan/bin
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.konan
          key: deps-v2-{{ checksum "build.gradle" }}

  publish:
    docker:
    - image: cibuilds/github:0.12
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts/libs
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(grep version <build.gradle | cut -c10- | rev | cut -c1- | rev)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/libs/*

workflows:
  version: 2
  everything:
    jobs:
      - build
      - publish:
          requires:
          - build
          filters:
            branches:
              only:
                - master
